CREATE TABLE ANNOUNCESYS (
ASID VARCHAR2(50),
ASPOINT SDO_GEOMETRY,
RADIUS NUMBER,
PRIMARY KEY (ASID));

INSERT INTO user_sdo_geom_metadata VALUES (
  'ANNOUNCESYS',
  'ASPOINT',
  SDO_DIM_ARRAY( 
    SDO_DIM_ELEMENT('X', 0, 820, 0.05),
    SDO_DIM_ELEMENT('Y', 0, 580, 0.05)
     ),NULL);

CREATE INDEX ASINDEX ON ANNOUNCESYS (ASPOINT) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE TABLE BUILDING (
BID VARCHAR2(50),
BNAME VARCHAR2(50),
NODENUMBER NUMBER,
SHAPE SDO_GEOMETRY,
PRIMARY KEY (BID));

INSERT INTO user_sdo_geom_metadata VALUES (
  'BUILDING',
  'SHAPE',
  SDO_DIM_ARRAY( 
    SDO_DIM_ELEMENT('X', 0, 820, 0.05),
    SDO_DIM_ELEMENT('Y', 0, 580, 0.05)
     ),NULL);


CREATE INDEX BINDEX ON BUILDING (SHAPE) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE TABLE STUDENT (
PID VARCHAR2(50),
PPOINT SDO_GEOMETRY,
PRIMARY KEY (PID));

INSERT INTO user_sdo_geom_metadata VALUES (
  'STUDENT',
  'PPOINT',
  SDO_DIM_ARRAY( 
    SDO_DIM_ELEMENT('X', 0, 820, 0.05),
    SDO_DIM_ELEMENT('Y', 0, 580, 0.05)
     ),NULL);


CREATE INDEX PINDEX ON STUDENT (PPOINT) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

